import { StyleSheet } from "react-native";
import type { ThemeColors } from "../../constants/theme";

export const createStyles = (c: ThemeColors, isMobile: boolean) =>
  StyleSheet.create({
    container: {
      width: isMobile ? 280 : 240,
      backgroundColor: c.sidebar,
      padding: 20,
      paddingTop: 24,
      justifyContent: "space-between",
      borderRightWidth: 1,
      borderRightColor: c.divider,
      ...(isMobile && {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        zIndex: 100,
        elevation: 10,
      }),
    },
    overlay: {
      position: "absolute",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      zIndex: 90,
    },
    brandRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 36,
    },
    brandLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    brandIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    brandIconText: { color: "#FFFFFF", fontSize: 18, fontWeight: "700" },
    logo: { color: c.text, fontSize: 16, fontWeight: "700" },
    tagline: {
      color: c.textMuted,
      fontSize: 9,
      letterSpacing: 1.5,
      fontWeight: "600",
    },
    closeButton: {
      padding: 8,
    },
    closeText: {
      color: c.textMuted,
      fontSize: 20,
    },
    menu: { gap: 4 },
    activeItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: c.surfaceHover,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
    },
    activeIcon: { fontSize: 16 },
    active: { color: c.primary, fontSize: 14, fontWeight: "600" },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
    },
    menuIcon: { fontSize: 16 },
    item: { color: c.textSecondary, fontSize: 14 },
    proCard: {
      backgroundColor: c.proCardBg,
      borderRadius: 14,
      padding: 18,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: c.proCardBorder,
    },
    proLabel: {
      color: c.primaryLight,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      marginBottom: 8,
    },
    proTitle: {
      color: c.text,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
      marginBottom: 14,
    },
    proButton: {
      backgroundColor: c.proBtnBg,
      paddingVertical: 10,
      borderRadius: 8,
      alignItems: "center",
    },
    proButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
    bottomLinks: { gap: 16 },
    bottomLink: { color: c.textSecondary, fontSize: 14 },
  });
